# Project identification
sonar.projectKey=flask-demo
sonar.projectName=Flask SonarQube Demo
sonar.projectVersion=1.0

# Project source settings
sonar.sources=.
sonar.language=py
sonar.python.version=3.9
sonar.sourceEncoding=UTF-8

# SonarQube server details
sonar.host.url=http://172.21.147.236:9000
sonar.login=sqp_24c54ee74e37e03644d56a46123be92b4d6f60d6

# Exclude unnecessary files
sonar.exclusions=**/__pycache__/**, **/*.test.py

# Test coverage report (if using pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml

