def imageName = 'flask-app'
def imageTobePush = 'abdulmusavvirrohe/srechallenge-flaskapp'
pipeline{
    agent any
    stages{
        stage('code checkout'){
            steps{
                checkout scm
            }
        }
        stage('unit test'){
            steps{
                sh "docker build -t ${imageName}:${env.BUILD_ID} -f Dockerfile ."
                sh "docker run --rm ${imageName} pytest"
            }
        }
        stage('image tagging'){
            sh "docker tag ${imageName}:${env.BUILD_ID} ${imageTobePush}:${env.BUILD_ID}"
        }
        stage('Image Push'){
            steps{
                withDockerRegistry(credentialsId: '06d4c5a6-00d8-4197-81bc-6f440dbe51fa', url: 'abdulmusavvirrohe/srechallenge') {
                    sh "docker push ${imageTobePush}:${env.BUILD_ID}"
                }
            }
        }
    }
    post{
        success{
            echo 'Docker image built, tested, tagged and pushed successfully'
        }
        failure{
            echo 'Pipeline failed'
        }
    }

}
